USE [DACN]
GO
/****** Object:  UserDefinedFunction [dbo].[AUTO_IDKH]    Script Date: 11/14/2022 1:36:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[AUTO_IDKH]()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MAKH) FROM KHACHHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAKH, 3)) FROM KHACHHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'KH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
/****** Object:  Table [dbo].[DICHVU]    Script Date: 11/14/2022 1:36:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DICHVU](
	[MADICHVU] [varchar](5) NOT NULL,
	[LOAIDICHVU] [nvarchar](30) NULL,
 CONSTRAINT [PK_DICHVU] PRIMARY KEY CLUSTERED 
(
	[MADICHVU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DUAN]    Script Date: 11/14/2022 1:36:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DUAN](
	[MADUAN] [varchar](5) NOT NULL,
	[LOAIDUAN] [nvarchar](30) NULL,
 CONSTRAINT [PK_DUAN] PRIMARY KEY CLUSTERED 
(
	[MADUAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 11/14/2022 1:36:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MAKH] [varchar](5) NOT NULL,
	[TENKH] [nvarchar](30) NOT NULL,
	[DIACHI] [nvarchar](50) NULL,
	[DT] [varchar](11) NULL,
	[EMAIL] [varchar](30) NULL,
	[MADICHVU] [varchar](5) NULL,
	[MADUAN] [varchar](5) NULL,
	[GHICHU] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 11/14/2022 1:36:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[idUser] [int] NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
	[Password] [nvarchar](50) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[idUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KHACHHANG] ADD  CONSTRAINT [IDKH]  DEFAULT ([DBO].[AUTO_IDKH]()) FOR [MAKH]
GO
ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD  CONSTRAINT [FK_KHACHHANG_DICHVU1] FOREIGN KEY([MADICHVU])
REFERENCES [dbo].[DICHVU] ([MADICHVU])
GO
ALTER TABLE [dbo].[KHACHHANG] CHECK CONSTRAINT [FK_KHACHHANG_DICHVU1]
GO
ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD  CONSTRAINT [FK_KHACHHANG_DUAN] FOREIGN KEY([MADUAN])
REFERENCES [dbo].[DUAN] ([MADUAN])
GO
ALTER TABLE [dbo].[KHACHHANG] CHECK CONSTRAINT [FK_KHACHHANG_DUAN]
GO
ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD  CONSTRAINT [CK_DienThoai] CHECK  (([DT] like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' OR [DT] like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' OR [DT] like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' OR [DT] like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[KHACHHANG] CHECK CONSTRAINT [CK_DienThoai]
GO
INSERT [dbo].[DICHVU] ([MADICHVU], [LOAIDICHVU], [MADUAN]) VALUES (N'DV1', N'THIETKE', NULL)
INSERT [dbo].[DICHVU] ([MADICHVU], [LOAIDICHVU], [MADUAN]) VALUES (N'DV2', N'THICONG', NULL)
INSERT [dbo].[DICHVU] ([MADICHVU], [LOAIDICHVU], [MADUAN]) VALUES (N'DV3', N'CAHAI', NULL)
GO
INSERT [dbo].[DUAN] ([MADUAN], [LOAIDUAN]) VALUES (N'BT', N'BIETTHU')
INSERT [dbo].[DUAN] ([MADUAN], [LOAIDUAN]) VALUES (N'CH', N'CANHO')
INSERT [dbo].[DUAN] ([MADUAN], [LOAIDUAN]) VALUES (N'NP', N'NHAPHO')
INSERT [dbo].[DUAN] ([MADUAN], [LOAIDUAN]) VALUES (N'PB', N'PHONGBEP')
INSERT [dbo].[DUAN] ([MADUAN], [LOAIDUAN]) VALUES (N'PK', N'PHONGKHACH')
INSERT [dbo].[DUAN] ([MADUAN], [LOAIDUAN]) VALUES (N'PN', N'PHONGNGU')
INSERT [dbo].[DUAN] ([MADUAN], [LOAIDUAN]) VALUES (N'PT', N'PHONGTAM')
INSERT [dbo].[DUAN] ([MADUAN], [LOAIDUAN]) VALUES (N'QCF', N'QUANCAFFE')
INSERT [dbo].[DUAN] ([MADUAN], [LOAIDUAN]) VALUES (N'SHOP', N'SHOP_THOITRANG')
INSERT [dbo].[DUAN] ([MADUAN], [LOAIDUAN]) VALUES (N'VP', N'VANPHONG')
GO